config/routes.rb
Rails.application.routes.draw do
  root 'jobs#view'
  resources :jobs

      get 'all_jobs' => 'jobs#view'
      get 'sorted_index' => 'jobs#sorted_index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  helper_method :sort_column, :sort_direction

  def index
    @jobs = Job.order(sort_column + " " + sort_direction)
  end

  def new
    @job = Job.new
  end

  def view
    @jobs = Job.all
  end

  def create
    Job.create(job_params)
    redirect_to all_jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.update(params[:id],job_params)
    redirect_to all_jobs_path
  end

  def destroy
    @job = Job.destroy(params[:id])
    redirect_to all_jobs_path
  end

  def show
    @job = Job.find(params[:id])
  end


  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

  def sort_column
    Job.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
  title ||= column.titleize
  direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
  link_to title, :sort => column, :direction => direction
end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>EDIT POSTING</h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<h1> RailsBridgeCorp Open Jobs </h1>
<tbody>
  <tr>
    <tb> <h2> <%= sortable "title" %> </h1> </tb>
  </tr>
    <% @jobs.each do |job| %>
  <tr>
    <tb> <h3><%= job.title %></h3> </tb>
    <tb> <h4><%= link_to "view", job %></h4> </tb>
  </tr>
    <% end %>
</tbody>

app/views/jobs/new.html.erb
<h1> Add a job </h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<p> cool </p> 

  <tbody>
      <tr>
        <tb> <h3><%= @job.title %></h3> </tb>
        <tb> <h3><%= @job.description %></h3></tb>
        <td> <h5><%= link_to "Edit Posting", edit_job_path(@job)%></h5> </td>
        <td> <h5><%= link_to 'Delete Posting', @job, method: :delete %></h5> </td>
    </tr>
  </tbody>

app/views/jobs/view.html.erb
<h1> RailsBridgeCorp Open Jobs </h1>
<tbody>
  <tr>
    <tb> <h2> COOL JOB BROH </h1> </tb>
  </tr>
<% @jobs.each do |job| %>

    <tr>
      <tb> <h3><%= job.title %></h3> </tb>
      <tb> <h4><%= link_to "view", job %></h4> </tb>
    </tr>
    <% end %>
</tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<header class='clearfix'>
<div class="left-nav">
  <ul>
    <li><%= link_to "Home", all_jobs_path %></li>
  </ul>
</div>
<div class="right-nav">
  <ul>
    <li><%= link_to "Add Job", new_job_path %></li>
  </ul>
</div>
</header>

<body>

<div class='content'>
<%= yield %>
</div>

</body>
</html>